return {
	{"George Orwell","1984",633},
	{"F. Scott Fitzgerald","The Great Gatsby",616},
	{"J.D. Salinger","The Catcher In The Rye",613},
	{"Fyodor Dostoyevsky","Crime And Punishment",573},
	{"Joseph Heller","Catch-22",550},
	{"Mark Twain","The Adventures Of Tom And Huck",549},
	{"Herman Melville","Moby-Dick",538},
	{"Gabriel Garcia Marquez","One Hundred Years Of Solitude",534},
	{"Harper Lee","To Kill A Mockingbird",527},
	{"John Steinbeck","The Grapes Of Wrath",521},
	{"Vladimir Nabokov","Lolita",521},
	{"Jane Austen","Pride And Prejudice",492},
	{"J.R.R. Tolkien","The Lord Of The Rings",489},
	{"Aldous Huxley","Brave New World",488},
	{"James Joyce","Ulysses",480},
	{"Charlotte Bronte","Jane Eyre",471},
	{"Emily Bronte","Wuthering Heights",459},
	{"Fyodor Dostoyevsky","The Brothers Karamazov",398},
	{"Charles Dickens","Great Expectations",396},
	{"Virginia Woolf","To The Lighthouse",395},
	{"Leo Tolstoy","War And Peace",382},
	{"Ernest Hemingway","The Sun Also Rises",382},
	{"William Faulkner","The Sound And The Fury",380},
	{"Lewis Carroll","Alice's Adventures In Wonderland",378},
	{"Mary Wollstonecraft Shelley","Frankenstein",359},
	{"Joseph Conrad","Heart Of Darkness",353},
	{"George Eliot","Middlemarch",352},
	{"George Orwell","Animal Farm",348},
	{"Miguel de Cervantes Saavedra","Don Quixote",346},
	{"Kurt Vonnegut","Slaughterhouse-Five",334},
	{"Victor Hugo","Les Misérables",325},
	{"J.K. Rowling","Harry Potter",320},
	{"C.S. Lewis","The Chronicles Of Narnia",320},
	{"Leo Tolstoy","Anna Karenina",317},
	{"William Golding","Lord Of The Flies",308},
	{"Ralph Ellison","Invisible Man",306},
	{"Henry James","The Golden Bowl",289},
	{"Vladimir Nabokov","Pale Fire",276},
	{"Margaret Mitchell","Gone With The Wind",266},
	{"Alexandre Dumas","The Count Of Monte Cristo",260},
	{"Douglas Adams","The Hitchhiker's Guide To The Galaxy",255},
	{"Laurence Sterne","The Life And Opinions Of Tristram Shandy, Gentleman",252},
	{"Gustave Flaubert","Madame Bovary",244},
	{"William Makepeace Thackery","Vanity Fair",237},
	{"Franz Kafka","The Trial",235},
	{"William Faulkner","Absalom, Absalom!",233},
	{"Jack London","The Call Of The Wild",232},
	{"Jane Austen","Emma",232},
	{"Toni Morrison","Beloved",229},
	{"Louisa May Alcott","Little Women",228},
	{"E.M. Forster","A Passage To India",224},
	{"Frank Herbert","Dune",215},
	{"James Joyce","A Portrait Of The Artist As A Young Man",215},
	{"Albert Camus","The Stranger",212},
	{"Ken Kesey","One Flew Over The Cuckoo's Nest",209},
	{"Fyodor Dostoyevsky","The Idiot",209},
	{"Bram Stoker","Dracula",206},
	{"Oscar Wilde","The Picture Of Dorian Gray",205},
	{"John Kennedy Toole","A Confederacy Of Dunces",197},
	{"Virginia Woolf","Mrs. Dalloway",193},
	{"Edith Wharton","The Age Of Innocence",193},
	{"Henry Fielding","The History Of Tom Jones, A Foundling",193},
	{"Malcolm Lowry","Under The Volcano",192},
	{"Homer","The Odyssey",190},
	{"Jonathan Swift","Gulliver's Travels",189},
	{"Marcel Proust","In Search Of Lost Time",188},
	{"Salman Rushdie","Midnight's Children",186},
	{"Theodore Dreiser","An American Tragedy",185},
	{"Markus Zusak","The Book Thief",182},
	{"Hermann Hesse","Siddhartha",180},
	{"Thomas Mann","The Magic Mountain",179},
	{"Chinua Achebe","Things Fall Apart",178},
	{"Henry Miller","Tropic Of Cancer",178},
	{"S.E. Hinton","The Outsiders",176},
	{"Jack Kerouac","On The Road",176},
	{"Antoine de Saint-Exupery","The Little Prince",175},
	{"Lois Lowry","The Giver",173},
	{"Evelyn Waugh","Brideshead Revisited",172},
	{"Anthony Burgess","A Clockwork Orange",172},
	{"E.B. White","Charlotte's Web",171},
	{"Henry James","The Ambassadors",171},
	{"David Foster Wallace","Infinite Jest",170},
	{"Edgar Allen Poe","The Complete Stories And Poems",167},
	{"Orson Scott Card","Ender's Saga",166},
	{"Truman Capote","In Cold Blood",165},
	{"Henry James","The Wings Of The Dove",164},
	{"Saul Bellow","The Adventures Of Augie March",163},
	{"William Faulkner","As I Lay Dying",162},
	{"Suzanne Collins","The Hunger Games",161},
	{"L.M. Montgomery","Anne Of Greene Gables",158},
	{"Ayn Rand","Atlas Shrugged",157},
	{"William Gibson","Neuromancer",157},
	{"Kathryn Stockett","The Help",156},
	{"George R.R. Martin","A Song Of Ice And Fire",156},
	{"Ford Madox Ford","The Good Soldier",155},
	{"Dan Brown","The Da Vinci Code",154},
	{"Robert Graves","I, Claudius",153},
	{"Jean Rhys","Wide Sargasso Sea",152},
	{"Henry James","The Portrait Of A Lady",151},
	{"Elizabeth Bowen","The Death Of The Heart",150},
	{"Dazai Osamu","No Longer Human",176},
	{"Nikolai Gogol","The Overcoat",35},
	{"Agatha Christie","And Then There Were None",272},
	{"Nathaniel Hawthorne","The Scarlet Letter",272}
}